# Generated by Django 3.2.4 on 2021-06-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_passengers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passengers',
            options={'verbose_name_plural': 'Passengers'},
        ),
    ]
