# Generated by Django 3.2.4 on 2021-06-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0003_alter_passengers_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengers',
            old_name='routes',
            new_name='lines',
        ),
    ]
