# Generated by Django 3.2.4 on 2021-06-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0004_rename_routes_passengers_lines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengers',
            old_name='lines',
            new_name='routes',
        ),
    ]
